Project-1-Wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "my_wiki"
urlpatterns = [
    path("", views.index, name="index"),
    ##adding url for the entry page
    path('wiki/<str:title>', views.entry, name='entry'),
    path("search/", views.search , name='search' ),
    path("create" , views.create, name="create" ),
    path("random" , views.random_page, name="random"),
    path("edit/<str:title>" ,views.edit, name='edit')
]

Project-1-Wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project-1-Wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Project-1-Wiki/encyclopedia/views.py
from django.shortcuts import render
from django.contrib import messages
from django import forms 
import random

from . import util

from markdown2 import Markdown
import difflib
markdowner = Markdown()

####utils variables and functions ###########
#status messages dict
status = {
    'save_s' : 'Saved Successfully',
    'save_w' : 'Already Exists',
    'save_e' : 'Error Saving',
    'edit_s' : 'Edited Successfully',
    'edit_e' : 'Error Editing',
    'form_e' : 'invalid Form',
    'exist_e': "Dont't exists",

}


# entries list
entries = util.list_entries()

#form object from django
class NewTaskForm(forms.Form):
    title = forms.CharField(label='title')
    content = forms.CharField(label='content')


#convert md to html
def get_html_from_md(md_title):
    html = util.get_entry(md_title)
    if html != None:
        html =  markdowner.convert(html)
    elif html == None:
        html = f" <img style='width:70%;' alt='Not Found' src='https://http.cat/404'>"
        status = False
    return html 

##############################################

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": entries
    })

def entry(request, title):
    html = get_html_from_md(title)
    return render(request, "encyclopedia/entry.html", {
        "title" : title,
        "content": html
    } )


def search(request):
    if request.method == "POST":
        query = request.POST['q']
        close_matchs = difflib.get_close_matches(query, entries , cutoff=0.6)
        if query in entries:
            html = get_html_from_md(query)
            return render(request, "encyclopedia/entry.html", {
                "title" : query,
                "content": html
            } )

        else :
            return render(request, "encyclopedia/search.html", {
                "query" : query,
                "results": close_matchs
            } )




def create(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            #### if entry don't already exists
            if title not in entries:
                #### create it
                try:
                    util.save_entry(title, content)
                except:
                    messages.error(request,  f"{status['save_e']} {title}")                
                    return render(request , "encyclopedia/create.html")

                messages.success(request,  f"{title} {status['save_s']} ")    
                return entry(request, title)            
            #else entry already exists
            else:
                messages.error(request, f'{ title } {status["save_w"]} ')
                return render(request, "encyclopedia/create.html")

        ##else form is not valid        
        else:
            messages.error(request, f" {status['form_e']} ")
            return render(request, "encyclopedia/create.html")
    else:
        return render(request, "encyclopedia/create.html")


########## Random
def random_page(request):
    page = random.choice(entries)
    return entry(request, title=page)


########## Edit

def edit(request, title):
    ##get request
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            ##edit if only wiki already exists
            if title in entries:
                try:
                    util.save_entry(title, content)
                except:
                    messages.error(request,  f" {status['edit_e']} {title} ")                
                    return render(request , "encyclopedia/edit.html")

                messages.success(request, f"{title}  {status['edit_s']} " )
                return entry(request, title=title)

            else:
                messages.error(request, f" wiki {status['exist_e']} ")
                return entry(request, title=title)

        else:
            messages.error(request, f" {status['form_e']} ")
            return render(request, "encyclopedia/edit.html")

    content =  util.get_entry(title)
    return render(request, "encyclopedia/edit.html", {
        'title': title,
        'content' : content
    } )

Project-1-Wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create
{% endblock %}

{% block header %}
    {% include "encyclopedia/messages.html" %}
{% endblock %} 


{% block body %}

<form action=" {% url 'my_wiki:create' %} " method="POST">
        {% csrf_token %}
    <div class="form-group">
      <label for="exampleFormControlInput1">Wiki's title </label>
      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="" name="title">
    </div>

    <div class="form-group">
      <label for="exampleFormControlTextarea1">Wiki's content</label>
      <textarea name='content' type="text" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>

    <div class="form-group">
        <input class="btn btn-primary mb-2" type="submit" id="submit1" value="create">
    </div>

  </form>
{% endblock %}

Project-1-Wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit - {{title}}
{% endblock %}

{% block header %}
    {% include "encyclopedia/messages.html" %}
{% endblock %} 


{% block body %}

<form action=" {% url 'my_wiki:edit' title %} " method="POST">
        {% csrf_token %}
    <div class="form-group">
      <label for="exampleFormControlInput1"> Editing {{ title }} </label>
      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="" name="title"  value=" {{ title }} " readonly>
    </div>

    <div class="form-group">
      <label for="exampleFormControlTextarea1">  {{title}}'s content</label>
      <textarea name='content' type="text" class="form-control" id="exampleFormControlTextarea1" rows="10"> {{ content }}</textarea>
    </div>

    <div class="form-group">
        <input class="btn btn-primary mb-2" type="submit" id="submit1" value="Edit">
    </div>

  </form>
{% endblock %}

Project-1-Wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}} - encyclopedia 
{% endblock %}

{% block header %}
    {% include "encyclopedia/messages.html" %}
{% endblock %} 

{% block body %}

    <div>
        {% if "https://http.cat/404" not in  content  %}
        
        <a href="{% url 'my_wiki:edit' title %}">Edit</a>

        {{ content | safe }}

        {% elif "https://http.cat/404" in content %}
        <center>    
        {{ content | safe }}
        </center>


        {% endif %}

    </div>

{% endblock %}

Project-1-Wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Project-1-Wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row" style="padding-left: 10px ;">
            <div class="sidebar col-lg-2 col-md-3">
                 {% block header %} {% endblock %} 
                <h2>Wiki</h2>
                <form method=POST action= "{% url 'my_wiki:search' %}">

                    {% csrf_token %}
                    <input  class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'my_wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href=" {% url 'my_wiki:create' %} ">  Create New Page</a>
                </div>
                <div>
                    <a href=" {% url 'my_wiki:random' %} "> Random Page </a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project-1-Wiki/encyclopedia/templates/encyclopedia/messages.html
{% if messages  %}

{% for message in messages %}
    <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
        {{ message }}
    </div>
{% endfor %}

{% endif %}

Project-1-Wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search - {{query}} 
{% endblock %}


{% block body %}
    <center>
        {% if query %}
            <h2>You searched for {{query}} </h2>

        {% else %}

            <h2>You forgot the enter a query </h2>

        {% endif %}

        <ul style="list-style: none;">
        {% for item in results %}
        <li>
            <a href="{% url 'my_wiki:entry' item %}">{{item}}</a>
        </li>
        {% endfor %}
        </ul>


    </center>



{% endblock %}